# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'urxui/mainwindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(825, 587)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 13, 1, 1, 1)
        self.minusRYButton = QtWidgets.QPushButton(self.centralWidget)
        self.minusRYButton.setObjectName("minusRYButton")
        self.gridLayout.addWidget(self.minusRYButton, 14, 0, 1, 1)
        self.minusRZButton = QtWidgets.QPushButton(self.centralWidget)
        self.minusRZButton.setObjectName("minusRZButton")
        self.gridLayout.addWidget(self.minusRZButton, 16, 0, 1, 1)
        self.minusZButton = QtWidgets.QPushButton(self.centralWidget)
        self.minusZButton.setObjectName("minusZButton")
        self.gridLayout.addWidget(self.minusZButton, 12, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 12, 1, 1, 1)
        self.poseLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.poseLineEdit.setObjectName("poseLineEdit")
        self.gridLayout.addWidget(self.poseLineEdit, 4, 1, 1, 5)
        self.minusRXButton = QtWidgets.QPushButton(self.centralWidget)
        self.minusRXButton.setObjectName("minusRXButton")
        self.gridLayout.addWidget(self.minusRXButton, 13, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.disconnectButton = QtWidgets.QPushButton(self.centralWidget)
        self.disconnectButton.setObjectName("disconnectButton")
        self.gridLayout.addWidget(self.disconnectButton, 0, 5, 1, 1)
        self.connectButton = QtWidgets.QPushButton(self.centralWidget)
        self.connectButton.setObjectName("connectButton")
        self.gridLayout.addWidget(self.connectButton, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.jointsLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.jointsLineEdit.setObjectName("jointsLineEdit")
        self.gridLayout.addWidget(self.jointsLineEdit, 5, 1, 1, 5)
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.addressLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.addressLineEdit.setObjectName("addressLineEdit")
        self.gridLayout.addWidget(self.addressLineEdit, 0, 0, 1, 4)
        self.minusXButton = QtWidgets.QPushButton(self.centralWidget)
        self.minusXButton.setObjectName("minusXButton")
        self.gridLayout.addWidget(self.minusXButton, 9, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 9, 1, 1, 1)
        self.plusXButton = QtWidgets.QPushButton(self.centralWidget)
        self.plusXButton.setObjectName("plusXButton")
        self.gridLayout.addWidget(self.plusXButton, 9, 2, 1, 1)
        self.minusYButton = QtWidgets.QPushButton(self.centralWidget)
        self.minusYButton.setObjectName("minusYButton")
        self.gridLayout.addWidget(self.minusYButton, 10, 0, 2, 1)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 10, 1, 1, 1)
        self.plusYButton = QtWidgets.QPushButton(self.centralWidget)
        self.plusYButton.setObjectName("plusYButton")
        self.gridLayout.addWidget(self.plusYButton, 10, 2, 1, 1)
        self.plusRXButton = QtWidgets.QPushButton(self.centralWidget)
        self.plusRXButton.setObjectName("plusRXButton")
        self.gridLayout.addWidget(self.plusRXButton, 13, 2, 1, 1)
        self.plusZButton = QtWidgets.QPushButton(self.centralWidget)
        self.plusZButton.setObjectName("plusZButton")
        self.gridLayout.addWidget(self.plusZButton, 12, 2, 1, 1)
        self.plusRYButton = QtWidgets.QPushButton(self.centralWidget)
        self.plusRYButton.setObjectName("plusRYButton")
        self.gridLayout.addWidget(self.plusRYButton, 14, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 14, 1, 1, 1)
        self.stateLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.stateLineEdit.setObjectName("stateLineEdit")
        self.gridLayout.addWidget(self.stateLineEdit, 3, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 16, 1, 1, 1)
        self.plusRZButton = QtWidgets.QPushButton(self.centralWidget)
        self.plusRZButton.setObjectName("plusRZButton")
        self.gridLayout.addWidget(self.plusRZButton, 16, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.csysLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.csysLineEdit.setObjectName("csysLineEdit")
        self.gridLayout.addWidget(self.csysLineEdit, 6, 1, 1, 4)
        self.csysButton = QtWidgets.QPushButton(self.centralWidget)
        self.csysButton.setObjectName("csysButton")
        self.gridLayout.addWidget(self.csysButton, 6, 5, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 825, 26))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Rx"))
        self.minusRYButton.setText(_translate("MainWindow", "-"))
        self.minusRZButton.setText(_translate("MainWindow", "-"))
        self.minusZButton.setText(_translate("MainWindow", "-"))
        self.label_5.setText(_translate("MainWindow", "Z"))
        self.minusRXButton.setText(_translate("MainWindow", "-"))
        self.label_2.setText(_translate("MainWindow", "Current joints"))
        self.disconnectButton.setText(_translate("MainWindow", "Disconnect"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.label_9.setText(_translate("MainWindow", "State:"))
        self.label.setText(_translate("MainWindow", "Current pose"))
        self.addressLineEdit.setText(_translate("MainWindow", "localhost"))
        self.minusXButton.setText(_translate("MainWindow", "-"))
        self.label_3.setText(_translate("MainWindow", "X"))
        self.plusXButton.setText(_translate("MainWindow", "+"))
        self.minusYButton.setText(_translate("MainWindow", "-"))
        self.label_4.setText(_translate("MainWindow", "Y"))
        self.plusYButton.setText(_translate("MainWindow", "+"))
        self.plusRXButton.setText(_translate("MainWindow", "+"))
        self.plusZButton.setText(_translate("MainWindow", "+"))
        self.plusRYButton.setText(_translate("MainWindow", "+"))
        self.label_7.setText(_translate("MainWindow", "Ry"))
        self.label_8.setText(_translate("MainWindow", "Rz"))
        self.plusRZButton.setText(_translate("MainWindow", "+"))
        self.label_10.setText(_translate("MainWindow", "Current CSys"))
        self.csysButton.setText(_translate("MainWindow", "Update Csys"))

