# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'urxui/mainwindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 611)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_3 = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addrComboBox = QtWidgets.QComboBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addrComboBox.sizePolicy().hasHeightForWidth())
        self.addrComboBox.setSizePolicy(sizePolicy)
        self.addrComboBox.setEditable(True)
        self.addrComboBox.setModelColumn(0)
        self.addrComboBox.setObjectName("addrComboBox")
        self.horizontalLayout.addWidget(self.addrComboBox)
        self.connectButton = QtWidgets.QPushButton(self.frame_5)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout.addWidget(self.connectButton)
        self.disconnectButton = QtWidgets.QPushButton(self.frame_5)
        self.disconnectButton.setObjectName("disconnectButton")
        self.horizontalLayout.addWidget(self.disconnectButton)
        self.gridLayout_3.addWidget(self.frame_5, 0, 0, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.stateLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.stateLineEdit.setReadOnly(True)
        self.stateLineEdit.setObjectName("stateLineEdit")
        self.gridLayout.addWidget(self.stateLineEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.poseLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.poseLineEdit.setReadOnly(True)
        self.poseLineEdit.setObjectName("poseLineEdit")
        self.gridLayout.addWidget(self.poseLineEdit, 1, 1, 1, 1)
        self.copyPoseButton = QtWidgets.QPushButton(self.frame_2)
        self.copyPoseButton.setObjectName("copyPoseButton")
        self.gridLayout.addWidget(self.copyPoseButton, 1, 2, 1, 1)
        self.jointsLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.jointsLineEdit.setReadOnly(True)
        self.jointsLineEdit.setObjectName("jointsLineEdit")
        self.gridLayout.addWidget(self.jointsLineEdit, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.copyJointsButton = QtWidgets.QPushButton(self.frame_2)
        self.copyJointsButton.setObjectName("copyJointsButton")
        self.gridLayout.addWidget(self.copyJointsButton, 2, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.csysButton = QtWidgets.QPushButton(self.frame_2)
        self.csysButton.setObjectName("csysButton")
        self.gridLayout.addWidget(self.csysButton, 3, 2, 1, 1)
        self.csysComboBox = QtWidgets.QComboBox(self.frame_2)
        self.csysComboBox.setEditable(True)
        self.csysComboBox.setObjectName("csysComboBox")
        self.gridLayout.addWidget(self.csysComboBox, 3, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 1, 0, 2, 1)
        self.stopButton = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout_3.addWidget(self.stopButton, 2, 1, 1, 1)
        self.gridLayout_7.addWidget(self.frame_3, 0, 0, 1, 2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.minusXButton = QtWidgets.QPushButton(self.frame_4)
        self.minusXButton.setObjectName("minusXButton")
        self.gridLayout_5.addWidget(self.minusXButton, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 1, 1, 1)
        self.plusXButton = QtWidgets.QPushButton(self.frame_4)
        self.plusXButton.setObjectName("plusXButton")
        self.gridLayout_5.addWidget(self.plusXButton, 0, 3, 1, 1)
        self.minusYButton = QtWidgets.QPushButton(self.frame_4)
        self.minusYButton.setObjectName("minusYButton")
        self.gridLayout_5.addWidget(self.minusYButton, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 1, 1, 2)
        self.plusYButton = QtWidgets.QPushButton(self.frame_4)
        self.plusYButton.setObjectName("plusYButton")
        self.gridLayout_5.addWidget(self.plusYButton, 1, 3, 1, 1)
        self.minusZButton = QtWidgets.QPushButton(self.frame_4)
        self.minusZButton.setObjectName("minusZButton")
        self.gridLayout_5.addWidget(self.minusZButton, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 2, 1, 1, 2)
        self.plusZButton = QtWidgets.QPushButton(self.frame_4)
        self.plusZButton.setObjectName("plusZButton")
        self.gridLayout_5.addWidget(self.plusZButton, 2, 3, 1, 1)
        self.minusRXButton = QtWidgets.QPushButton(self.frame_4)
        self.minusRXButton.setObjectName("minusRXButton")
        self.gridLayout_5.addWidget(self.minusRXButton, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 3, 1, 1, 1)
        self.plusRXButton = QtWidgets.QPushButton(self.frame_4)
        self.plusRXButton.setObjectName("plusRXButton")
        self.gridLayout_5.addWidget(self.plusRXButton, 3, 2, 1, 2)
        self.minusRYButton = QtWidgets.QPushButton(self.frame_4)
        self.minusRYButton.setObjectName("minusRYButton")
        self.gridLayout_5.addWidget(self.minusRYButton, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 4, 1, 1, 1)
        self.plusRYButton = QtWidgets.QPushButton(self.frame_4)
        self.plusRYButton.setObjectName("plusRYButton")
        self.gridLayout_5.addWidget(self.plusRYButton, 4, 3, 1, 1)
        self.minusRZButton = QtWidgets.QPushButton(self.frame_4)
        self.minusRZButton.setObjectName("minusRZButton")
        self.gridLayout_5.addWidget(self.minusRZButton, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 5, 1, 1, 1)
        self.plusRZButton = QtWidgets.QPushButton(self.frame_4)
        self.plusRZButton.setObjectName("plusRZButton")
        self.gridLayout_5.addWidget(self.plusRZButton, 5, 3, 1, 1)
        self.gridLayout_2.addWidget(self.frame_4, 0, 2, 4, 1)
        self.toolRefCheckBox = QtWidgets.QCheckBox(self.frame)
        self.toolRefCheckBox.setObjectName("toolRefCheckBox")
        self.gridLayout_2.addWidget(self.toolRefCheckBox, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.accLineEdit = QtWidgets.QLineEdit(self.frame)
        self.accLineEdit.setObjectName("accLineEdit")
        self.gridLayout_2.addWidget(self.accLineEdit, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.velLineEdit = QtWidgets.QLineEdit(self.frame)
        self.velLineEdit.setObjectName("velLineEdit")
        self.gridLayout_2.addWidget(self.velLineEdit, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.tab_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.decJ3Button = QtWidgets.QPushButton(self.frame_7)
        self.decJ3Button.setObjectName("decJ3Button")
        self.gridLayout_6.addWidget(self.decJ3Button, 5, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_7)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 5, 1, 1, 1)
        self.incJ3Button = QtWidgets.QPushButton(self.frame_7)
        self.incJ3Button.setObjectName("incJ3Button")
        self.gridLayout_6.addWidget(self.incJ3Button, 5, 2, 1, 2)
        self.decJ4Button = QtWidgets.QPushButton(self.frame_7)
        self.decJ4Button.setObjectName("decJ4Button")
        self.gridLayout_6.addWidget(self.decJ4Button, 6, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_7)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 6, 1, 1, 1)
        self.decJ2Button = QtWidgets.QPushButton(self.frame_7)
        self.decJ2Button.setObjectName("decJ2Button")
        self.gridLayout_6.addWidget(self.decJ2Button, 3, 0, 1, 1)
        self.decJ0Button = QtWidgets.QPushButton(self.frame_7)
        self.decJ0Button.setObjectName("decJ0Button")
        self.gridLayout_6.addWidget(self.decJ0Button, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_7)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 0, 1, 1, 1)
        self.decJ1Button = QtWidgets.QPushButton(self.frame_7)
        self.decJ1Button.setObjectName("decJ1Button")
        self.gridLayout_6.addWidget(self.decJ1Button, 2, 0, 1, 1)
        self.decJ5Button = QtWidgets.QPushButton(self.frame_7)
        self.decJ5Button.setObjectName("decJ5Button")
        self.gridLayout_6.addWidget(self.decJ5Button, 7, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_7)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 7, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_7)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 2, 1, 1, 1)
        self.incJ2Button = QtWidgets.QPushButton(self.frame_7)
        self.incJ2Button.setObjectName("incJ2Button")
        self.gridLayout_6.addWidget(self.incJ2Button, 3, 2, 1, 2)
        self.incJ1Button = QtWidgets.QPushButton(self.frame_7)
        self.incJ1Button.setObjectName("incJ1Button")
        self.gridLayout_6.addWidget(self.incJ1Button, 2, 2, 1, 2)
        self.incJ0Button = QtWidgets.QPushButton(self.frame_7)
        self.incJ0Button.setObjectName("incJ0Button")
        self.gridLayout_6.addWidget(self.incJ0Button, 0, 2, 1, 2)
        self.incJ4Button = QtWidgets.QPushButton(self.frame_7)
        self.incJ4Button.setObjectName("incJ4Button")
        self.gridLayout_6.addWidget(self.incJ4Button, 6, 2, 1, 2)
        self.incJ5Button = QtWidgets.QPushButton(self.frame_7)
        self.incJ5Button.setObjectName("incJ5Button")
        self.gridLayout_6.addWidget(self.incJ5Button, 7, 2, 1, 2)
        self.gridLayout_4.addWidget(self.frame_7, 1, 2, 3, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_6)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 1, 0, 1, 1)
        self.jointAccLineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.jointAccLineEdit.setObjectName("jointAccLineEdit")
        self.gridLayout_4.addWidget(self.jointAccLineEdit, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 4, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_6)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 2, 0, 1, 1)
        self.jointVelLineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.jointVelLineEdit.setObjectName("jointVelLineEdit")
        self.gridLayout_4.addWidget(self.jointVelLineEdit, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_7.addWidget(self.tabWidget, 1, 0, 2, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.tab_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dio0CheckBox = QtWidgets.QCheckBox(self.frame_8)
        self.dio0CheckBox.setObjectName("dio0CheckBox")
        self.verticalLayout_4.addWidget(self.dio0CheckBox)
        self.dio1CheckBox = QtWidgets.QCheckBox(self.frame_8)
        self.dio1CheckBox.setObjectName("dio1CheckBox")
        self.verticalLayout_4.addWidget(self.dio1CheckBox)
        self.dio2CheckBox = QtWidgets.QCheckBox(self.frame_8)
        self.dio2CheckBox.setObjectName("dio2CheckBox")
        self.verticalLayout_4.addWidget(self.dio2CheckBox)
        self.dio3CheckBox = QtWidgets.QCheckBox(self.frame_8)
        self.dio3CheckBox.setObjectName("dio3CheckBox")
        self.verticalLayout_4.addWidget(self.dio3CheckBox)
        self.dio4CheckBox = QtWidgets.QCheckBox(self.frame_8)
        self.dio4CheckBox.setObjectName("dio4CheckBox")
        self.verticalLayout_4.addWidget(self.dio4CheckBox)
        self.dio5CheckBox = QtWidgets.QCheckBox(self.frame_8)
        self.dio5CheckBox.setObjectName("dio5CheckBox")
        self.verticalLayout_4.addWidget(self.dio5CheckBox)
        self.dio6CheckBox = QtWidgets.QCheckBox(self.frame_8)
        self.dio6CheckBox.setObjectName("dio6CheckBox")
        self.verticalLayout_4.addWidget(self.dio6CheckBox)
        self.dio7CheckBox = QtWidgets.QCheckBox(self.frame_8)
        self.dio7CheckBox.setObjectName("dio7CheckBox")
        self.verticalLayout_4.addWidget(self.dio7CheckBox)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.gridLayout_7.addWidget(self.tabWidget_2, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 24))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.disconnectButton.setText(_translate("MainWindow", "Disconnect"))
        self.label_9.setText(_translate("MainWindow", "Running:"))
        self.label.setText(_translate("MainWindow", "Current pose:"))
        self.copyPoseButton.setText(_translate("MainWindow", "Copy"))
        self.label_2.setText(_translate("MainWindow", "Current joints:"))
        self.copyJointsButton.setText(_translate("MainWindow", "Copy"))
        self.label_10.setText(_translate("MainWindow", "Current CSys:"))
        self.csysButton.setText(_translate("MainWindow", "Update Csys"))
        self.stopButton.setText(_translate("MainWindow", "STOP!"))
        self.minusXButton.setText(_translate("MainWindow", "-"))
        self.label_3.setText(_translate("MainWindow", "X"))
        self.plusXButton.setText(_translate("MainWindow", "+"))
        self.minusYButton.setText(_translate("MainWindow", "-"))
        self.label_4.setText(_translate("MainWindow", "Y"))
        self.plusYButton.setText(_translate("MainWindow", "+"))
        self.minusZButton.setText(_translate("MainWindow", "-"))
        self.label_5.setText(_translate("MainWindow", "Z"))
        self.plusZButton.setText(_translate("MainWindow", "+"))
        self.minusRXButton.setText(_translate("MainWindow", "-"))
        self.label_6.setText(_translate("MainWindow", "Rx"))
        self.plusRXButton.setText(_translate("MainWindow", "+"))
        self.minusRYButton.setText(_translate("MainWindow", "-"))
        self.label_7.setText(_translate("MainWindow", "Ry"))
        self.plusRYButton.setText(_translate("MainWindow", "+"))
        self.minusRZButton.setText(_translate("MainWindow", "-"))
        self.label_8.setText(_translate("MainWindow", "Rz"))
        self.plusRZButton.setText(_translate("MainWindow", "+"))
        self.toolRefCheckBox.setText(_translate("MainWindow", "Tool reference"))
        self.label_14.setText(_translate("MainWindow", "Default acceleration (m/s2)"))
        self.label_11.setText(_translate("MainWindow", "Default velocity (m/s)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Linear move"))
        self.decJ3Button.setText(_translate("MainWindow", "-"))
        self.label_17.setText(_translate("MainWindow", "3"))
        self.incJ3Button.setText(_translate("MainWindow", "+"))
        self.decJ4Button.setText(_translate("MainWindow", "-"))
        self.label_18.setText(_translate("MainWindow", "4"))
        self.decJ2Button.setText(_translate("MainWindow", "-"))
        self.decJ0Button.setText(_translate("MainWindow", "-"))
        self.label_13.setText(_translate("MainWindow", "0"))
        self.decJ1Button.setText(_translate("MainWindow", "-"))
        self.decJ5Button.setText(_translate("MainWindow", "-"))
        self.label_19.setText(_translate("MainWindow", "5"))
        self.label_16.setText(_translate("MainWindow", "2"))
        self.label_15.setText(_translate("MainWindow", "1"))
        self.incJ2Button.setText(_translate("MainWindow", "+"))
        self.incJ1Button.setText(_translate("MainWindow", "+"))
        self.incJ0Button.setText(_translate("MainWindow", "+"))
        self.incJ4Button.setText(_translate("MainWindow", "+"))
        self.incJ5Button.setText(_translate("MainWindow", "+"))
        self.label_20.setText(_translate("MainWindow", "Default acceleration (rad/s2)"))
        self.label_21.setText(_translate("MainWindow", "Default velocity (rad/s)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Joint move"))
        self.dio0CheckBox.setText(_translate("MainWindow", "0"))
        self.dio1CheckBox.setText(_translate("MainWindow", "1"))
        self.dio2CheckBox.setText(_translate("MainWindow", "2"))
        self.dio3CheckBox.setText(_translate("MainWindow", "3"))
        self.dio4CheckBox.setText(_translate("MainWindow", "4"))
        self.dio5CheckBox.setText(_translate("MainWindow", "5"))
        self.dio6CheckBox.setText(_translate("MainWindow", "6"))
        self.dio7CheckBox.setText(_translate("MainWindow", "7"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Digital IO"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Analog IO"))

